### ISSUE TITLE
Text getting cropped when it shouldn't

### ISSUE THREAD

**Issue by BritishPiper** [grimfang4/SDL_FontCache#26]
To replicate this, just switch the "FreeSans.ttf" from the example given in the repository with the attached font "bugged font.ttf". The text gets cropped such as in this image -> 
![image](https://user-images.githubusercontent.com/5056011/45578428-e052fa00-b857-11e8-81e5-1ba7c7b090e4.png)

I tried to simplify by just calling FC_CreateFont, FC_LoadFont and FC_Draw, but the text still gets cropped -> 
![image](https://user-images.githubusercontent.com/5056011/45578491-548d9d80-b858-11e8-9611-3b86cc4eb54a.png)

By using just SDL_ttf (TTF_OpenFont, TTF_RenderText_Solid, ...), I was able to correctly print the font to screen (lazy foo example) -> 
![image](https://user-images.githubusercontent.com/5056011/45578577-c2d26000-b858-11e8-97e5-e299955a60c4.png)

[bugged font.zip](https://github.com/grimfang4/SDL_FontCache/files/2385104/bugged.font.zip)

**Comment by grimfang4** [comment]
This is fixed in ae2af360deaf98a3c98a9a65d07add60ce49c297 for the particular problem this font is having.  I can't be sure of the underlying cause without analyzing the font or digging into FreeType, but SDL_ttf is reporting the height incorrectly.  My fix just gets a different height measurement if it can tell that something is wrong.  Please close if you can verify.

**Comment by BritishPiper** [comment]
The bug is now fixed for this font and other similar bugged fonts.
