### ISSUE TITLE
Size of Wrapped Text

### ISSUE THREAD

**Issue by SimonDoesGit** [grimfang4/SDL_FontCache#34]
How can I get the size of wrapped text without rendering via **FC_DrawColumn**?

**Comment by grimfang4** [comment]
FC_DrawColumn() assumes you know what the width of the column is.  You can use that width in FC_GetColumnHeight() to get the other dimension.

Just because it's a related use-case, I should also mention that FC_GetCharacterOffset() can be used to tell where to draw a text editing cursor and FC_GetPositionFromOffset() can be used to convert mouse click coordinates into a character index.

**Comment by SimonDoesGit** [comment]
Thank you
