### ISSUE TITLE
Line splitting in FC_DrawBox (and variants)

### ISSUE THREAD

**Issue by TG-Galeforce** [grimfang4/SDL_FontCache#36]
I'm currently working on supporting Japanese text in one of my games. The Japanese language does not use spaces, and therefore FC_DrawBox puts long bodies of text into one line instead of splitting them. Thus, I'd like to know where the line splitting happens in your code so that I can modify that functionality to start new lines at arbitrary characters (instead of just whitespace) if the language is Japanese. Can you please point me to where I should look? Thank you in advance.

**Comment by grimfang4** [comment]
Fortunately, I just touched this with the last changeset and made it easier to extend.  Look at SDL_FontCache.c lines 1066 and 1885.  For a general solution, I would think that a customizable array of word-breaking characters would work well.

For Japanese, it might just be best to add an option to break on every character.

**Comment by TG-Galeforce** [comment]
Ah, thank you for addressing this! For some reason, I was never alerted of your reply, so I didn't know until now that you'd done it...please accept my very belated gratitude.

**Comment by jdearborn** [comment]
No problem. :)
For reference, that commit was f1a34802e3b2ae1fb3b4f5bc67e37331fe878809, where a utility function was added to detect and preserve breaking spaces that FC_GetBufferFitToColumn() would use instead of assuming " ".  The next step would be to either hardcode your own breaking space characters (find "Add any characters here that should make separate words") or add functions/options to specify the characters or that all characters should break words.

**Comment by grimfang4** [comment]
No problem. :)
For reference, that commit was f1a3480, where a utility function was added to detect and preserve breaking spaces that FC_GetBufferFitToColumn() would use instead of assuming " ". The next step would be to either hardcode your own breaking space characters (find "Add any characters here that should make separate words") or add functions/options to specify the characters or that all characters should break words.

**Comment by TG-Galeforce** [comment]
Understood; I will try these steps. Thank you again.
